name: Build Wheels

on:
  pull_request: {}
  workflow_call:

jobs:
  build-wheels:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, macos-12, windows-latest]
        python: [cp39, cp310, cp311, cp312, cp313]
        arch: [x86_64, amd64]
        exclude:
          - os: macos-12
            arch: amd64
          - os: ubuntu-22.04
            arch: amd64
          - os: windows-latest
            arch: x86_64
    env:
      CIBW_BUILD: ${{ matrix.python }}*${{ matrix.arch }}
      CIBW_SKIP: "*-musllinux_*"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9 # This might need to be dynamic based on the matrix
      - name: Install cibuildwheel
        run: pip install cibuildwheel
      - name: Build wheels
        run: cibuildwheel --output-dir wheelhouse
      - uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}-${{ matrix.python }}-${{ matrix.arch }}
          path: ./wheelhouse/*.whl
